services:
  api:
    build: ./back_end
    command: nodemon -L server.js
    ports:
      - "5000:5000"
    volumes:
      - ./back_end:/usr/src/app
      
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db


