# POST http://localhost:5000/api/posts
# Content-Type: application/json

# {
    
#     "user_id": "6659289507708713c0e3103e",
#     "content": "How are you today"
    
# }

# DELETE http://localhost:5000/api/posts/665a5ab6b294477b83f213a1

# Update a post by ID
# PUT http://localhost:5000/api/posts/665a5ab6b294477b83f213a1
# Content-Type: application/json

# {
#     "content": "Test test test"
# }


# # #Read a single post by ID
# GET http://localhost:5000/api/posts/665a5ad2b294477b83f213a3
# Content-Type: application/json

# # #Read all posts
# GET http://localhost:5000/api/posts
# Content-Type: application/json

GET  http://localhost:5000/api/test/testAPI
